# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='visit_type',
            field=models.CharField(choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
