# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-24 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0002_diagnosis_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='possible_diagnosis',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
