# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-24 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0006_auto_20180124_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='result',
        ),
        migrations.AddField(
            model_name='labresult',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnoses.LabTest'),
        ),
    ]
