# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-21 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('patient_code', models.CharField(max_length=40)),
                ('mobile_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('insurance_number', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to=patients.models.patient_directory_path)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_companies.InsuranceCompany')),
            ],
        ),
    ]
